language: node_js
node_js:
  - 12
before_install:
  - echo "registry=https://npm.pkg.github.com/babajidemm" >.npmrc
  - echo "@babajidemm:registry=https://npm.pkg.github.com/:_authToken=\${GITHUB_TOKEN}" > .npmrc
script:
  - npm test
after_success: npm run coverage
