version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
	        # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          pre-steps:
            - run:
              command: npm config set registry https://npm.pkg.github.com/babajidemm
            - run:
              command: echo "registry=https://npm.pkg.github.com/babajidemm" > web_ui/frontend/.npmrc
            - run:
              command: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > web_ui/frontend/.npmrc
