# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Authenticate with GitHub package registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > ~/.npmrc
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm config set registry http://registry.npmjs.org
      - run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "@babajidemm:registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: echo "@babajidemm:registry=https://registry.npmjs.org/" > /home/runner/work/_temp/.npmrc
      - run: echo "registry=https://registry.npmjs.org/" > /home/runner/work/_temp/.npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > /home/runner/work/_temp/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > /home/runner/work/_temp/.npmrc
      - run: echo "$(cat ~/.npmrc)"
      - run: echo "$(cat /home/runner/work/_temp/.npmrc)"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@babajidemm'
      - run: npm config set registry http://registry.npmjs.org
      - run: echo "registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "@babajidemm:registry=https://registry.npmjs.org/" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > ~/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: echo "@babajidemm:registry=https://registry.npmjs.org/" > /home/runner/work/_temp/.npmrc
      - run: echo "registry=https://registry.npmjs.org/" > /home/runner/work/_temp/.npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.MY_GITHUB_TOKEN }}" > /home/runner/work/_temp/.npmrc
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > /home/runner/work/_temp/.npmrc
      - run: echo "$(cat ~/.npmrc)"
      - run: echo "$(cat /home/runner/work/_temp/.npmrc)"
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
          MY_GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}
